name: Build and Deploy VuePress
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: HollowLatte/Note-Book
        TARGET_BRANCH: github-pages
        BUILD_SCRIPT: npm install -g pnpm && pnpm install && pnpm run docs:build
        BUILD_DIR: ./dist
